name: Deploy

on:
  push:
  schedule:
    - cron: '0 15 * * 1'

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to AliYun Container Registry
      uses: docker/login-action@v1 
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_CR_USERNAME }}
        password: ${{ secrets.ALIYUN_CR_TOKEN }}
    - name: Bionic
      uses: docker/build-push-action@v3
      with:
        context: ./mirror
        file: ./mirror/Dockerfile.bionic
        push: true
        tags: |
          stardustdl/dev-containers:mirror-bionic
          registry.cn-hangzhou.aliyuncs.com/stardustdl/dev-containers:mirror-bionic
    - name: C
      uses: docker/build-push-action@v3
      with:
        context: ./c
        file: ./c/Dockerfile
        push: true
        tags: |
          stardustdl/dev-containers:c
          registry.cn-hangzhou.aliyuncs.com/stardustdl/dev-containers:c
